name: Gear-Academy-homework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  homework_test:
    name: Run checks and tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Set up Rust
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown  
      
    - name: Check and test
      run: |
        cargo fmt --all --check
        cargo clippy --all-targets -- -D warnings -A unused-imports
        cargo t
